name: Update Dog

on:  
  schedule:
    - cron: "0 */6 * * *"
  push:

jobs:
  update_doggo:
    name: "Update Doggo"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: Update README.md
        run: |
          pip3 install -r requirements.txt
          python3 replace_image.py
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "Automated dog update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}